sudo: required
language: python
services:
- docker
script:
- docker build .
deploy:
  provider: heroku
  api_key:
    secure: "%{HEROKU_API_KEY}"
  app: glyph-docs
  run: heroku container:push web --arg SERVER_HOST="%{SERVER_HOST}"
  on:
    branch: master
    repo: Himenon/glyph-docs
