version: '2.1'

services:
  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile.mkdocs
    working_dir: /src/
    command: mkdocs serve --dev-addr 0.0.0.0:8000 --livereload
    ports:
    - 8000:8000
    volumes:
      - ./mkdocs:/src