site_name: WEB技術調査ドキュメント
site_description: mkdocsでホスティングされています。
site_author: HimenoGlyph

repo_name: glyph-docs
repo_url: https://github.com/Himenon/glyph-docs
edit_uri: edit/master/mkdocs/docs

dev_addr: 127.0.0.1:8080

markdown_extensions:
  - fontawesome_markdown

theme: material

extra_css: []

extra_javascript: []

markdown_extensions:
  - admonition
  - markdown_include.include:
      base_path: docs
  - codehilite:
      linenums: true

google_analytics: ['UA-55455343-6', 'glyph-docs.herokuapp.com']

pages:
- 'index.md'
- '新着':
  - 'news/css-traking.md'
- 'MkDocs':
  - 'mkdocs/mkdocs-qa.md'
  - 'mkdocs/deploy-mkdocs-to-heroku.md'
