site_name: 技術調査用リポジトリ
site_description: mkdocsでホスティングされています。
site_author: HimenoGlyph

repo_name: glyph-docs
repo_url: https://github.com/Himenon/glyph-docs
edit_uri: edit/master/mkdocs/docs

dev_addr: 127.0.0.1:8080

markdown_extensions:
  - fontawesome_markdown

theme: material

extra_css: []

extra_javascript: []

markdown_extensions:
  - admonition
  - markdown_include.include:
      base_path: docs
  - codehilite:
      linenums: true

pages:
- 'index.md'
- 'mkdocs-qa.md'
